[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed= 115200
lib_deps = 
  ; adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
  bodmer/TFT_eSPI @ ^2.5.43
    ; adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
  https://github.com/garhul/GrblParser#9108f54
  makuna/NeoPixelBus@^2.7.3  
  robtillaart/PCF8575@^0.1.10
  robtillaart/ADS1X15 @ ^0.5.0
  Wire
  SPI

build_flags = 
  -D ESP8266=1
